// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwowxjwcwbdxhiwaypos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3b3d4andjd2JkeGhpd2F5cG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzI5MzAsImV4cCI6MjA2MjE0ODkzMH0.QC5pD-3xkxwQmSZhN8sMCuVi4qA-vGaykpRvALdqFmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);